on:
  push:
    branches: [build]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'
      
    - name: 🔨 Build Project
      run: |
        cd teach_for_all
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 31.31.196.23
        port: 21
        protocol: FTP
        username: u1615416_ahtem
        password: ${{secrets.password}}
        local-dir: ./teach_for_all/dist/
